# Generated by Django 5.2.1 on 2025-06-04 01:39

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=catalogo.models.get_upload_path),
        ),
    ]
